feat: Symfony 7.0 support
coopTilleuls/CoopTilleulsForgotPasswordBundle pull request #134
Opened 2023-12-20 18:35 UTC by grosmanal

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT

This PR allows this bundle to be used with Symfony 7.0

2023-12-21 07:54 UTC, vincentchalamon commented
Nice! Thanks @grosmanal.
Can you also update the .github/workflows/ci.yml to replace Symfony 6.3 by 6.4 (LTS), and add Symfony 7.0 in the matrix, please?

2023-12-24 16:18 UTC, grosmanal commented
Converting to draft, because `behat/behat` and `friends-of-behat/symfony-extension` need to be updated to support Symfony 7.

2024-01-10 10:39 UTC, hanovruslan commented
Hi, guys! Any progress here?

2024-01-13 15:18 UTC, grosmanal commented
If the tests are green, I'll squash the commits. @vincentchalamon

2024-01-14 13:33 UTC, vincentchalamon requested changes

2024-01-14 13:33 UTC, vincentchalamon commented on composer.json
>          "jms/serializer-bundle": "^1.4 || ^2.3 || ^3.0 || ^4.0",
```suggestion
        "jms/serializer-bundle": "^1.4 || ^2.3 || ^3.0 || ^4.0 || ^5.0",
```

2024-01-14 13:50 UTC, vincentchalamon approved these changes

2024-01-14 13:50 UTC, merged

2024-01-14 13:50 UTC, vincentchalamon commented
Thanks @grosmanal! :rocket:

2024-01-14 13:54 UTC, vincentchalamon commented
Published on v1.5.3

2024-01-15 07:06 UTC, hanovruslan commented
Thanks a lot!