Symfony 6
coopTilleuls/CoopTilleulsForgotPasswordBundle pull request #88
Opened 2022-01-18 06:38 UTC by jongotlin

| Q             | A
| ------------- | ---
| Bug fix?      |no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT

Not 100% sure this is all it takes to make it work in Symfony 6. At least main functionality is working in my Symfony 6 app.

2022-01-18 08:12 UTC, vincentchalamon requested changes
Great work, thank you very much @jongotlin!
Some minor changes, and the CI is failing, but then I think it'll be ok :-)

2022-01-18 08:12 UTC, vincentchalamon commented on EventListener/MainRequestTrait.php
> +    protected function isMainRequest(KernelEvent $event): bool
```suggestion
    private function isMainRequest(KernelEvent $event): bool
```

2022-01-18 08:12 UTC, vincentchalamon commented on .github/workflows/ci.yml
>            - '5.3.*'
```suggestion
          - '5.4.*'
```

2022-01-18 08:12 UTC, vincentchalamon commented on .github/workflows/ci.yml
>              symfony: '5.3.*'
```suggestion
            symfony: '5.4.*'
```

2022-01-18 08:12 UTC, vincentchalamon commented on .github/workflows/ci.yml
>              bootable: true
```suggestion
            bootable: true
            quality: true
```

2022-01-18 08:12 UTC, vincentchalamon commented on .github/workflows/ci.yml
> +        if: matrix.php >= '7.4'
```suggestion
        if: matrix.quality
```

2022-01-18 08:39 UTC, vincentchalamon commented
You gonna need to also update the DocumentationNormalizer and the AppKernel files:
> Method "Symfony\Component\Serializer\Normalizer\NormalizerInterface::supportsNormalization()" might add "bool" as a native return type declaration in the future. Do the same in implementation "CoopTilleuls\ForgotPasswordBundle\Bridge\ApiPlatform\Serializer\DocumentationNormalizer" now to avoid errors or add an explicit @return annotation to suppress this message.

> PHP Fatal error:  Declaration of AppKernel::getProjectDir() must be compatible with Symfony\Component\HttpKernel\Kernel::getProjectDir(): string in /home/runner/work/CoopTilleulsForgotPasswordBundle/CoopTilleulsForgotPasswordBundle/features/app/AppKernel.php on line 43

2022-01-19 19:44 UTC, jongotlin commented
Thank you for your review @vincentchalamon! Couldn't get the tests pass on sf 6. Can you help out? Otherwise I'll dig into it some more in the next couple of days.

2022-01-28 09:46 UTC, jongotlin commented
Got stuck with this one and would appreciate some help to get the tests pass with Symfony 6.

2022-01-28 10:37 UTC, vincentchalamon commented
@jongotlin I've commited some modifications on AppKernel to unstuck this PR. Could you have a look at the failing tests please? Should be easier now

2022-01-28 12:12 UTC, jongotlin commented
Thank you @vincentchalamon! Fixed the remaining stuff.

2022-01-28 12:12 UTC, vincentchalamon approved these changes

2022-01-28 12:13 UTC, merged

2022-01-28 12:13 UTC, vincentchalamon commented
Great job, thank you very much @jongotlin !